ALTER TABLE "Shop" ADD COLUMN "billingPlan"    TEXT NOT NULL DEFAULT 'free';
ALTER TABLE "Shop" ADD COLUMN "monthlyCharges" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Shop" ADD COLUMN "chargesResetAt" TIMESTAMP(3);
